select s.student_name, d.department_name from Student s left join Department d on s.department_id = d.department_id;
select st.staff_name, d.department_name from Staff st left join Department d on st.department_id = d.department_id;
select d.department_name from Department d left join Student s on d.department_id = s.department_id where s.student_id IS NULL;
select s.student_name from Student s left join Mark m on s.student_id = m.student_id where m.student_id IS NULL;
select s.student_name from Student s left join Mark m on s.student_id = m.student_id where m.student_id IS NULL;
select d.department_name,     AVG(s.cgpa) as avg_cgpa from Department d left join Student s on d.department_id = s.department_id GROUP BY d.department_name;
select d.department_name,   AVG(s.cgpa) as avg_cgpa from Department d JOIN Student s on d.department_id = s.department_id GROUP BY d.department_name HAVING AVG(s.cgpa) > 8.0;
select d.department_name,  COUNT(s.student_id) as total_students from Department d left join Student s on d.department_id = s.department_id GROUP BY d.department_name;
select su.subject_name,  MAX(m.marks) as highest_marks,  MIN(m.marks) as lowest_marks from Subject su JOIN Mark m on su.subject_id = m.subject_id GROUP BY su.subject_name;
select DISTINCT s.student_name from Student s JOIN Mark m on s.student_id = m.student_id where m.marks > 90;
select s.student_name from Student s JOIN Department d on s.department_id = d.department_id where d.department_name = 'Computer Science';
select s.student_name from Student s JOIN Department d on s.department_id = d.department_id where d.department_name = 'Computer Science';
select s.student_name,  SUM(m.marks) as total_marks from Student s left join Mark m on s.student_id = m.student_id GROUP BY s.student_name;
select d.department_name, COUNT(st.staff_id) as staff_count from Department d JOIN Staff st on d.department_id = st.department_id GROUP BY d.department_name HAVING COUNT(st.staff_id) > 2;
select student_name, cgpa from Student where cgpa > ( select AVG(cgpa) from Student);
select st.staff_name,  st.salary, st.department_id from Staff st JOIN (  select department_id,  AVG(salary) as avg_salary  from Staff GROUP BY department_id) a on st.department_id = a.department_id where st.salary > a.avg_salary; 
select MAX(salary) as second_highest_salary from Staff where salary < (  select MAX(salary) from Staff );
select s.student_name,   su.subject_name,  m.marks from Mark m JOIN Student s on m.student_id = s.student_id JOIN Subject su on m.subject_id = su.subject_id where m.marks = ( select MAX(m2.marks) from Mark m2 where m.subject_id = m2.subject_id );	
select s.student_name,  m.subject_id,  m.marks from Student s left join Mark m on s.student_id = m.student_id;
select  su.subject_name, AVG(m.marks) as avg_marks from Subject su INNER JOIN Mark m on su.subject_id = m.subject_id GROUP BY su.subject_name HAVING AVG(m.marks) < 70;
select department_id,SUM(salary) as total_salary from Staff GROUP BY department_id;
select department_id,SUM(salary) as total_salary from Staff GROUP BY department_id HAVING SUM(salary)>200000;
select * from Student where admission_year>2021 AND cgpa>7.5;
select admission_year,COUNT(*) as total_students from Student GROUP BY admission_year ORDER BY admission_year;
select city,COUNT(*) as total_students from Student GROUP BY city ORDER BY total_students DESC LIMIT 1;
select d.department_id,d.department_name,COUNT(s.staff_id) as staff_count from Department d left join Staff s on d.department_id=s.department_id GROUP BY d.department_id,d.department_name;
select DISTINCT s.student_id,s.student_name from Student s JOIN Mark m on s.student_id=m.student_id where m.marks<50;
select * from Staff where hire_date<'2018-01-01';
select DISTINCT d.department_id,d.department_name from Department d where d.department_id NOT IN (select department_id from Staff where salary IS NULL);
select student_id,student_name,cgpa,ROW_NUMBER() over(ORDER BY cgpa DESC) as row_num from Student;
select student_id,student_name,cgpa,RANK() over(ORDER BY cgpa DESC) as student_rank from Student;
select staff_id,staff_name,salary,DENSE_RANK() over(ORDER BY salary DESC) as dense_rank_salary from Staff;
select * from (select student_id,subject_id,marks,ROW_NUMBER() over(ORDER BY marks DESC) as rn from Mark) t where rn<=3;
select student_id,exam_date,marks,SUM(marks) over(partition by student_id ORDER BY exam_date) as running_total from Mark;
select subject_id,student_id,marks,AVG(marks) over(partition by subject_id) as avg_subject_marks from Mark;
select student_id,exam_date,marks,LAG(marks) over(partition by student_id ORDER BY exam_date) as previous_marks from Mark;
select student_id,exam_date,marks,LEAD(marks) over(partition by student_id ORDER BY exam_date) as next_marks from Mark;
select student_id,subject_id,marks,MAX(marks) over(partition by subject_id) as highest_marks from Mark;
select exam_date,student_id,marks,AVG(marks) over(ORDER BY exam_date) as cumulative_avg from Mark;
select * from (select student_id,student_name,department_id,admission_year,ROW_NUMBER() over(partition by department_id ORDER BY admission_year) as rn from Student) t where rn=1;
select * from (select staff_id,staff_name,department_id,hire_date,ROW_NUMBER() over(partition by department_id ORDER BY hire_date DESC) as rn from Staff) t where rn=1;
select student_id,student_name,cgpa,NTILE(4) over(ORDER BY cgpa DESC) as quartile from Student;
select student_id,student_name,cgpa,PERCENT_RANK() over(ORDER BY cgpa DESC) as percentage_rank from Student;
select staff_id,staff_name,salary,CUME_DIST() over(ORDER BY salary DESC) as cumulative_distribution from Staff;
select * from (select student_id,subject_id,marks,AVG(marks) over(partition by subject_id) as avg_marks from Mark) t where marks>avg_marks;
select department_id,AVG(salary) as avg_salary from Staff GROUP BY department_id HAVING AVG(salary)>(select AVG(salary) from Staff);
select s.student_id,s.student_name,m.marks from Student s JOIN Mark m on s.student_id=m.student_id where m.marks>(select AVG(m2.marks) from Mark m2 JOIN Student s2 on m2.student_id=s2.student_id where s2.department_id=s.department_id);
select * from (select student_id,subject_id,marks,DENSE_RANK() over(ORDER BY marks DESC) as rnk from Mark) t where rnk=3;
select department_id,AVG(salary) as avg_salary from Staff GROUP BY department_id HAVING AVG(salary)>(select AVG(salary) from Staff);
select s.student_id,s.student_name,m.marks from Student s JOIN Mark m on s.student_id=m.student_id where m.marks>(select AVG(m2.marks) from Mark m2 JOIN Student s2 on m2.student_id=s2.student_id where s2.department_id=s.department_id);
select * from (select student_id,subject_id,marks,DENSE_RANK() over(ORDER BY marks DESC) as rnk from Mark) t where rnk=3;
select s.student_name,d.department_name,sub.subject_name,m.exam_type,m.marks,AVG(m.marks) over(partition by d.department_id) as dept_avg_marks,RANK() over(ORDER BY m.marks DESC) as overall_rank from Student s JOIN Department d on s.department_id=d.department_id JOIN Mark m on s.student_id=m.student_id JOIN Subject sub on m.subject_id=sub.subject_id;