select * from Employees where salary IS NULL;
select * from Orders where discount IS NOT NULL;
select * from Products where category IS NULL;
select COUNT(*) AS total_null_managers from Employees where manager_id IS NULL;
select emp_id,name,IFNULL(salary,0) AS salary from Employees;
select emp_id,name,IFNULL(bonus,1000) AS bonus from Employees;
select order_id,customer_name,IFNULL(amount,500) AS amount from Orders;
select product_name,IFNULL(stock,0) AS stock from Products;
select emp_id,name,COALESCE(salary,bonus) AS earnings from Employees;
select emp_id,name,COALESCE(salary,bonus,0) AS income from Employees;
select product_name,COALESCE(price,1000) AS final_price from Products;
select customer_name,COALESCE(amount,discount,0) AS payment from Orders;
select emp_id,name,NULLIF(salary,0) AS salary from Employees;
select order_id,NULLIF(discount,0) AS discount from Orders;
select amount/NULLIF(discount,0) AS result from Orders;
select order_id,NULLIF(coupon_code,'DISC10') AS coupon_code from Orders;
select emp_id,name,IFNULL(salary,0)+IFNULL(bonus,0) AS total_earnings from Employees;
select * from Employees where salary IS NULL AND bonus IS NULL;
select * from Products where price IS NULL AND category IS NOT NULL;
select * from Orders where amount IS NULL AND discount IS NULL;
select emp_id,name,COALESCE(salary,bonus,1000) AS income from Employees;
select order_id,NULLIF(discount,0) AS discount from Orders;
select order_id,customer_name,IFNULL(amount,0)-IFNULL(discount,0) AS final_amount from Orders;
select * from Employees where salary IS NULL AND manager_id IS NOT NULL;