select * from Employees;
select emp_name, salary from Employees;
select emp_name, department from Employees;
select *from Employees where department = 'IT';
select emp_name, experience from Employees;
select *from Employees where salary > 70000;
select *from Employees where city = 'Hyderabad';
select * from Employees where experience < 4;
select * from Employees where department = 'Finance';
select * from Employees where salary = 52000;
select department, SUM(salary) as total_salary from Employees GROUP BY department;
select department, AVG(salary) as average_salary from Employees GROUP BY department;
select city, COUNT(*) as employee_count from Employees GROUP BY city;
select department, MAX(salary) as max_salary from Employees GROUP BY department;
select department, MIN(experience) as min_experience from Employees GROUP BY department;
select department, COUNT(*) as employee_count from Employees GROUP BY department HAVING COUNT(*) > 3;
select department, AVG(salary) as average_salary from Employees GROUP BY department HAVING AVG(salary) > 60000;
select city, COUNT(*) as employee_count from Employees GROUP BY city  HAVING COUNT(*) > 2;
select department, SUM(salary) as total_salary from Employees GROUP BY department HAVING SUM(salary) > 200000;
select department, MAX(salary) as max_salary from Employees GROUP BY department HAVING MAX(salary) > 90000;
select * from Employees ORDER BY salary DESC LIMIT 5;
select * from Employees ORDER BY experience DESC LIMIT 3;
select *from Employees where department = 'Finance' ORDER BY salary DESC LIMIT 2;
select * from Employees where city = 'Hyderabad' LIMIT 4;
select * from Employees ORDER BY salary DESC LIMIT 1;
select DISTINCT department from Employees;
select DISTINCT city from Employees;
select DISTINCT salary from Employees;
select DISTINCT department, city from Employees;
select DISTINCT experience from Employees;
select * from Employees where salary >= 80000;
select *from Employees where experience <= 3;
select * from Employees where salary <> 45000;
select * from Employees where salary < 50000;
select * from Employees where experience > 5;
select * from Employees where department = 'IT' AND salary > 70000;
select * from Employees where city = 'Hyderabad' OR city = 'Bangalore';
select * from Employees where department = 'HR' AND experience < 3;
select *from Employees where salary > 60000 OR experience > 6;
select * from Employees where department <> 'Sales';
select * from Employees where city IN ('Hyderabad', 'Mumbai');
select * from Employees where department IN ('IT', 'Finance');
select *from Employees where city NOT IN ('Chennai', 'Pune');
select * from Employees where salary IN (45000, 75000, 91000);
select * from Employees where department NOT IN ('HR', 'Sales');
select * from Employees where salary BETWEEN 50000 AND 80000;
select * from Employees where experience BETWEEN 3 AND 6;
select *from Employees where emp_id BETWEEN 105 AND 112;
select *from Employees where salary NOT BETWEEN 40000 AND 60000;
select *from Employees where experience BETWEEN 2 AND 4;
select *from Employees where emp_name LIKE 'R%';
select *from Employees where emp_name LIKE '%a';
select * from Employees where emp_name LIKE '%v%';
select *from Employees where city LIKE 'B%';
select *from Employees where department LIKE '%s';