select VERSION();
select  employee_name, department, salary, ROW_NUMBER() over (ORDER BY salary DESC) as row_num from employees;
select employee_name, salary, DENSE_RANK() over (ORDER BY salary DESC) as drank from employees;
select *from ( select employee_name, salary, ROW_NUMBER() over (ORDER BY salary DESC) as rn  from employees) t where rn <= 3;
select employee_name,department, salary, RANK() over ( PARTITION BY department ORDER BY salary DESC ) as dept_rank from employees;
select  employee_name, department, salary, MAX(salary) over ( PARTITION BY department   ) as highest_salary from employees;
select  order_id, order_date, total_amount, SUM(total_amount) over (  ORDER BY order_date ) as running_total from orders; 
select   employee_id, order_id, order_date, total_amount, SUM(total_amount) over ( PARTITION BY employee_id ORDER BY order_date ) as cumulative_sales from orders;
select  customer_id, order_id, order_date, total_amount, LAG(total_amount) over (     PARTITION BY customer_id   ORDER BY order_date ) as previous_order from orders;
select  customer_id, order_id, order_date, total_amount, LEAD(total_amount) over (  PARTITION BY customer_id  ORDER BY order_date ) as next_order from orders;
select  customer_id, order_id, total_amount,  total_amount - LAG(total_amount) over (      PARTITION BY customer_id   ORDER BY order_date   ) as amount_difference from orders;
select  order_id, order_date, total_amount, AVG(total_amount) over (  ORDER BY order_date  ROWS BETWEEN 2 PRECEDING AND CURRENT ROW ) as moving_avg from orders;
select  employee_name, salary,  NTILE(4) over (ORDER BY salary DESC) as quartile from employees;
select *from (  select   customer_id,  order_id, order_date, ROW_NUMBER() over ( PARTITION BY customer_id   ORDER BY order_date ) as rn from orders) t where rn = 1;
select *from ( select   customer_id,  order_id, order_date, ROW_NUMBER() over (  PARTITION BY customer_id  ORDER BY order_date DESC ) as rn from orders) t where rn = 1;
select  employee_name, department, salary, AVG(salary) over (   PARTITION BY department ) as dept_avg_salary from employees;
select * from ( select     employee_name,    department,    salary,   AVG(salary) over (        PARTITION BY department   ) as dept_avg   from employees) t where salary > dept_avg;
select   employee_name,  department,  salary,  SUM(salary) over (      PARTITION BY department  ) as department_payroll from employees;
select  employee_name, department, salary, ROUND( salary * 100.0 /  SUM(salary) over (PARTITION BY department),   2   ) as salary_percentage from employees;
select   employee_name, department, COUNT(*) over () as total_employees from employees;
with employee_sales as ( select  employee_id, SUM(total_amount) as total_sales from orders GROUP BY employee_id) select * from employee_sales;
with employee_sales as ( select  employee_id, SUM(total_amount) as total_sales from orders GROUP BY employee_id), avg_sales as (  select AVG(total_sales) as avg_total_sales from employee_sales) select  es.employee_id,  e.employee_name,  es.total_sales from employee_sales es JOIN employees e ON es.employee_id = e.employee_id CROSS JOIN avg_sales where es.total_sales > avg_sales.avg_total_sales;
with customer_spending as (select  customer_id,  SUM(total_amount) as total_spent  from orders  GROUP BY customer_id ),ranked_customers as ( select   customer_id,  total_spent,  RANK() over (  ORDER BY total_spent DESC ) as spending_rank from customer_spending) select * from ranked_customers;
with RECURSIVE numbers as ( select 1 as num  UNION ALL  select num + 1  from numbers where num < 10)select * from numbers;
with RECURSIVE employee_hierarchy as (  select     employee_id,  employee_name,  manager_id,  1 as level  from employees  where manager_id IS NULL UNION ALL  select   e.employee_id,  e.employee_name,   e.manager_id,   eh.level + 1  from employees e  JOIN employee_hierarchy eh  ON e.manager_id = eh.employee_id)select * from employee_hierarchy;
with avg_order as ( select AVG(total_amount) as avg_amount  from orders) select   o.*from orders o CROSS JOIN avg_order where o.total_amount > avg_amount;
with customer_totals as ( select  customer_id,  SUM(total_amount) as total_spending from orders GROUP BY customer_id) select   customer_id,  total_spending, RANK() over ( ORDER BY total_spending DESC ) as spending_rank from customer_totals;
select * from ( select   employee_name, department, salary, DENSE_RANK() over (   PARTITION BY department  ORDER BY salary DESC  ) as rnk from employees) t where rnk = 2;
select  employee_name, department, salary, MAX(salary) over (  PARTITION BY department ) - salary as salary_difference from employees;
with employee_sales as ( select   e.employee_id,  e.employee_name,  e.department,  SUM(o.total_amount) as total_sales from employees e JOIN orders o ON e.employee_id = o.employee_id  GROUP BY e.employee_id, e.employee_name, e.department), ranked_employees as (  select *,   RANK() over (  PARTITION BY department  ORDER BY total_sales DESC ) as sales_rank  from employee_sales) select * from ranked_employees where sales_rank = 1;